# Generated by Django 5.2 on 2025-06-05 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('blooms_level', models.CharField(choices=[('R', 'Remembering'), ('U', 'Understanding'), ('A', 'Applying'), ('AN', 'Analyzing'), ('E', 'Evaluating'), ('C', 'Creating')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='Teaching Point Text')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('student_class', models.CharField(max_length=20)),
                ('subjects', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='choice_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPointQuestionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionbank')),
                ('teaching_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.teachingpoint')),
            ],
            options={
                'unique_together': {('question', 'teaching_point')},
            },
        ),
    ]
